---
abstract: "Build CHANGES file from a project's git log using git log format."
author:
  - 'Kathryn Andersen'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101880, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-GitFmtChanges
requires:
  Text::Wrap: 2006.1117
resources:
  repository: http://github.com/rubykat/dzp-GitFmtChanges
version: 0.003
